server:
  port: 8089
#  address: 127.0.0.1

spring:
  application:
    name: Auth-Authentication-Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true
  config:
    import: configserver:http://localhost:8085
logging:
  level:
    com.netflix.eureka: debug
    feign: debug
    root: INFO
    com.auth_am.AM.controllers: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always
#resilience4j:
#  circuitbreaker:
#    instances:
#      property_tax_fallback:
#        register-health-indicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 6s
#        permittedNumberOfCallsInHalfOpenState: 5
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
